---
db_user: wordpress
db_pass: wordpress
db_name: wordpress

mysql_replication_primary: db01.{{ domain_name }}
mysql_replication_user: replicate
mysql_replication_user_password: "{{ replication_passwd }}"
